### ISSUE TITLE
Your Module 2 Assignment Link

### ISSUE THREAD

**Issue by davideavaldez** [ipika777/assignment1#1]
Your assignment was given to me for peer review. Unfortunately, the link that you provided does not lead to an actual site. Instead, it sends you to your repository. Did you make it into a site? If so, could you please provide the correct link?

The link should look something like this: http://yourusername.github.io/assignment1.

**Comment by ipika777** [comment]
Hi David, here is the link:

http://ipika777.github.io/assignment1/   

sorry it took some time..

Thanks, Iryna
